<?php require_once 'header.phtml' ?>
<!--//if(empty($categories)){ esto se hace en el model -->
  
<section class="productos-destacados">
  <h1 class="titulo-productos-destacados">PRODUCTOS MAS DESTACADOS</h1>

  <?php foreach ($products as $product) : ?>
    <!-- hacer un if(parametro === $category->nombre_categoria) muestro los productos con esa categoria-->

    <?php if ($product->categoria == $categoryId) : ?>

      <div class="cards">
        <div class="caja-foto-remera" style="width: auto; height: 362.764px; background-color: #1c1c1c;">

        </div>
        <a href="detalle/<?= $product->id_producto ?>">
          <div class="btn-agregar-carrito">
            <svg class="svg-carrito" xmlns="http://www.w3.org/2000/svg" width="" height="30" viewBox="0 0 256 256">
              <path fill="currentColor" d="M216 64h-40a48 48 0 0 0-96 0H40a16 16 0 0 0-16 16v120a16 16 0 0 0 16 16h176a16 16 0 0 0 16-16V80a16 16 0 0 0-16-16Zm-88-32a32 32 0 0 1 32 32H96a32 32 0 0 1 32-32Zm88 168H40V80h40v16a8 8 0 0 0 16 0V80h64v16a8 8 0 0 0 16 0V80h40Z" />
            </svg>
          </div>
        </a>
        <div class="info-de-producto">
          <h2 class="titulo-remeras"> <?= $product->nombre_categoria ?> </h2>
          <h5 class="nombre-remeras"> <?= $product->nombre ?> </h5>
          <p class="svg-dinero"><span class="iconify" data-icon="material-symbols:attach-money-rounded"></span>$<?= $product->precio ?></p>
        </div>
      </div>
    <?php endif ?>
  <?php endforeach ?>

</section>