<?php require_once 'header.phtml' ?>

<h1>Detalle del Ítem</h1>
<p>ID del ítem: <?= $product->id_producto ?></p>
<p>ID del ítem: <?= $product->id_producto ?></p>













<!-- cuando pongo http://localhost/TPE-web2/detalle me aparece con el css, pero cuando -->
<!-- lo pongo con parametro http://localhost/TPE-web2/detalle/4 me aparece todo bien pero sin css -->

<!-- preguntar lo de base url del head que no lo puse, esta en wpp filmina 21 ruteo esta -->