<div class="contenedor-footer">
    <footer>
      <div class="informacion">
        <p>&copy; 2023 FreshStyle. Todos los derechos reservados.</p>
      </div>
      <h4 class="footer-titulos">Navegación</h4>
      <div class="navegacion-footer">
        <ul>
          <li><a href="#">Inicio</a></li>
          <li><a href="#">productos</a></li>
          <li><a href="#">Contacto</a></li>
        </ul>
      </div>

      <div class="metodos-de-pago">
        <h4 class="footer-titulos">MEDIOS DE PAGO</h4>
        <div class="fotos">
          <img class="fotos-pago" src="img/logoCDNI.png" alt="logo cuenta dni">
          <img class="fotos-pago" src="img/LemonLogo.png" alt="Logo de lemon cash">
          <img class="fotos-pago" src="img/MercadoPagoLogo.webp" alt="logo mercadoPago">
        </div>
      </div>
      <div class="contacto">
        <h4 class="footer-titulos">CONTACTANOS</h4>
        <div class="redes-sociales">
          <div class="ig-y-wpp">
            <a href="https://wa.me/+54 9 2494657148?text=Hola, todo bien?" class="icono-wpp" target="_blank">
              <iconify-icon icon="logos:whatsapp-icon"></iconify-icon>
            </a>
            <a href="https://www.instagram.com/fresh.style._/" class="icono-instagram" target="_blank">
              <iconify-icon icon="skill-icons:instagram"></iconify-icon>
            </a>
          </div>
          <a class="gmail" href=""><iconify-icon icon="fa-regular:envelope"></iconify-icon>fresh.style2409@gmail.com</a>
        </div>
      </div>
    </footer>
  </div>