<!DOCTYPE html>
<html lang="en">

<head>
  <base href="<?= BASE_URL ?>">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fresh Style</title>
  <link rel="stylesheet" href="styles/estilo.css">
  <!-- tipografia -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect"
    href="https://fonts.gstatic.                                                                                                           com"
    crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Montserrat+Subrayada:wght@700&family=UnifrakturCook:wght@700&display=swap"
    rel="stylesheet"> <!--Script para crear los íconos de las redes sociales en el footer-->
  <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
</head>

<body>
  <!-- Header -->
  <header>
    <!-- boton del menu desplegable  -->
    <div class="contenedor-header">
      <label for="btn-menu">
        <div class="btn-menu">
          <iconify-icon icon="lucide:menu">
          </iconify-icon>
        </div>
      </label>
      <div class="company-name">
        <img class="imagen-logo" src="/img/logo header.png" alt="logo de Fresh Style">
        <div class="nombre-empresa">
          <h2>FreshStyle</h2>
        </div>
      </div>
      <div class="carrito">
        <a href="compra">
          <svg class="svg-carrito" xmlns="http://www.w3.org/2000/svg" width="" height="30" viewBox="0 0 256 256">
            <path fill="currentColor"
              d="M216 64h-40a48 48 0 0 0-96 0H40a16 16 0 0 0-16 16v120a16 16 0 0 0 16 16h176a16 16 0 0 0 16-16V80a16 16 0 0 0-16-16Zm-88-32a32 32 0 0 1 32 32H96a32 32 0 0 1 32-32Zm88 168H40V80h40v16a8 8 0 0 0 16 0V80h64v16a8 8 0 0 0 16 0V80h40Z" />
          </svg>
        </a>
      </div>
    </div>
    <!-- Menu desplegable -->
    <input type="checkbox" name="" id="btn-menu">
    <div class="container-menu">
      <div class="cont-menu">
        <nav>
          <a href="#">Ver todos los productos</a>
          <a href="#">Remeras</a>
          <a href="#">Buzos</a>
          <a href="#">Pantalones</a>
        </nav>
        <label for="btn-menu" class="icon-equis"><iconify-icon icon="fa6-solid:x"></iconify-icon> </label>
      </div>
    </div>
  </header>
  <!-- Fin del header -->
























<header>
    <!-- boton del menu desplegable  -->
    <div class="contenedor-header">
      <label for="btn-menu">
        <div class="btn-menu">
          <iconify-icon icon="lucide:menu">
          </iconify-icon>
        </div>
      </label>
      <div class="company-name">
        <img class="imagen-logo" src="/img/logo header.png" alt="logo de Fresh Style">
        <div class="nombre-empresa">
          <h2>FreshStyle</h2>
        </div>
      </div>
      <div class="carrito">
        <a href="compra">
          <svg class="svg-carrito" xmlns="http://www.w3.org/2000/svg" width="" height="30" viewBox="0 0 256 256">
            <path fill="currentColor"
              d="M216 64h-40a48 48 0 0 0-96 0H40a16 16 0 0 0-16 16v120a16 16 0 0 0 16 16h176a16 16 0 0 0 16-16V80a16 16 0 0 0-16-16Zm-88-32a32 32 0 0 1 32 32H96a32 32 0 0 1 32-32Zm88 168H40V80h40v16a8 8 0 0 0 16 0V80h64v16a8 8 0 0 0 16 0V80h40Z" />
          </svg>
        </a>
      </div>
    </div>
    <!-- Menu desplegable -->
    <input type="checkbox" name="" id="btn-menu">
    <div class="container-menu">
      <div class="cont-menu">
        <nav>
          <a href="#">Ver todos los productos</a>
          <a href="categoria/remeras">Remeras</a>
          <a href="categoria/buzos">Buzos</a>
          <a href="categoria/pantalones">Pantalones</a>
        </nav>
        <label for="btn-menu" class="icon-equis"><iconify-icon icon="fa6-solid:x"></iconify-icon> </label>
      </div>
    </div>
  </header>