
<?php require_once 'header.phtml' ?>

<section class="presentacion">
    <img class="img-presentacion" src="/img/94fca81d12c45d40950904c2e09c16a9.jpg" alt="">
    <img class="logo-parte-de-abajo" src="/img/parte de abajo del logo (1).png" alt="">
</section>

<section class="ir-a-productos-especificos">
    <div class="container-remeras">
      <a href="/public/index.html">
        <img src="/img/foto boton hypervinculo remeras (1).png" alt="">
      </a>
    </div>
    
<?php require_once 'templates/btns-categories.phtml' ?>
</section>

<?php require_once 'templates/products.phtml' ?>

<?php require_once 'templates/footer.phtml' ?>