<?php require_once 'templates/header.phtml'; ?>

<section class="presentacion">
    <img class="img-presentacion" src="/img/94fca81d12c45d40950904c2e09c16a9.jpg" alt="">
    <img class="logo-parte-de-abajo" src="/img/parte de abajo del logo (1).png" alt="">
</section>

<button><a href="logout">Cerrar Sesion</a></button>
<section class="ir-a-productos-especificos">
    <div class="container-remeras">
      <a href="/public/index.html">
        <img src="/img/foto boton hypervinculo remeras (1).png" alt="">
      </a>
    </div>
<a href="datosProductos"><button class="btn-productos-especificos" style="height: auto;">modificaciones Productos</button></a>
<a href="datosCategorias"><button class="btn-productos-especificos" style="height: auto;">modificaciones Categorias</button></a>
<?php require_once 'templates/btns-categories.phtml' ?>
</section>


<?php require_once 'templates/products.phtml' ?>
<?php require_once 'templates/footer.phtml'; ?>